# Build ASP.NET Core project and Docker image on every commit to master branch

variables:
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: Any CPU
- name: BuildProjects
  value: PlanningPokerCore.sln
- group: DockerSettings

trigger:
- master

pr: none

jobs:
- template: azure-pipelines-build.yml
  parameters:
    RunEnd2EndTests: true
    PublishArtifacts: true
    BuildDockerImage: true
