# Build Docker image using Azure Pipelines

jobs:
- job: PlanningPokerDocker
  displayName: PlanningPoker Docker
  dependsOn: PlanningPokerApp

  pool:
    vmImage: ubuntu-latest

  workspace:
    clean: all

  variables:
    DockerImageTagPrefix: b

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifact: web'
    inputs:
      artifactName: web
      downloadPath: $(System.BinariesDirectory)

  - task: ExtractFiles@1
    displayName: Extract web.zip
    inputs:
      archiveFilePatterns: $(System.BinariesDirectory)/web/web.zip
      destinationFolder: $(System.DefaultWorkingDirectory)/docker/app

  - task: Docker@2
    displayName: Build Docker image
    inputs:
      containerRegistry: $(DockerRegistryEndpointName)
      Dockerfile: docker/Dockerfile
      repository: $(DockerRepositoryName)
      tags: '$(DockerImageTagPrefix)$(Build.BuildId)'
